DSCI/STAT 8950 - Data Science Capstone Project

Merging tow data sets

In [ ]:
import os
for f in os.listdir("/content/"):
    print(f)

.config
MembershipByGradeRaceAndGender_20212022.csv
2023-2024_Free_and_Reduced_Lunch_Counts_by_School.xlsx
MembershipByGradeRaceAndGender_20232024.csv
MembershipByGradeRaceAndGender_20192020.csv
2018-19_Free_and_Reduced_Lunch_Counts_by_School.xls
MembershipByGradeRaceAndGender_20182019.csv
MembershipByGradeRaceAndGender_20242025.csv
2020-21_Free_and_Reduced_Lunch_Counts_by_School.xls
2021-2022_Free_and_Reduced_Lunch_Counts_by_School.xlsx
MembershipByGradeRaceAndGender_20222023.csv
2022-2023_Free_and_Reduced_Lunch_Counts_by_School.xlsx
MembershipByGradeRaceAndGender_20202021.csv
2019-20_Free_and_Reduced_Lunch_Counts_by_School.xls
2024-2025_Free_and_Reduced_Lunch_Counts_by_School.xlsx
sample_data

In [ ]:
frl = pd.read_excel("/content/2018-19_Free_and_Reduced_Lunch_Counts_by_School.xls")
print(frl.columns.tolist())

mem = pd.read_csv("/content/MembershipByGradeRaceAndGender_20182019.csv")
print(mem.columns.tolist())

[]
['DATAYEARS', 'CO_DIST', 'DISTRICT_NAME', 'COUNTY_NAME', 'CLASS_CODE', 'DISTRICT_TYPE_CODE', 'CO_DIST_SCH', 'COUNTY', 'DISTRICT', 'SCHOOL', 'SCHOOL_NAME', 'GRADE_CODE', 'F_WH', 'M_WH', 'FBL', 'M_BL', 'F_HI', 'M_HI', 'F_AS', 'M_AS', 'F_AM', 'M_AM', 'F_PI', 'M_PI', 'F_MU', 'M_MU', 'FEMALE_TOTAL', 'MALE_TOTAL', 'TOTAL']

In [ ]:
print("FRL columns:")
for c in frl.columns:
    print(c)

print("\nMEM columns:")
for c in mem.columns:
    print(c)

FRL columns:

MEM columns:
DATAYEARS
CO_DIST
DISTRICT_NAME
COUNTY_NAME
CLASS_CODE
DISTRICT_TYPE_CODE
CO_DIST_SCH
COUNTY
DISTRICT
SCHOOL
SCHOOL_NAME
GRADE_CODE
F_WH
M_WH
FBL
M_BL
F_HI
M_HI
F_AS
M_AS
F_AM
M_AM
F_PI
M_PI
F_MU
M_MU
FEMALE_TOTAL
MALE_TOTAL
TOTAL

In [ ]:
print("FRL columns:")
for c in frl.columns:
    print(c)

FRL columns:

In [ ]:
xl = pd.ExcelFile("/content/2018-19_Free_and_Reduced_Lunch_Counts_by_School.xls")
print(xl.sheet_names)

['Warning', ' Schools Data ', 'Districts Data ']

In [ ]:
frl = pd.read_excel("/content/2018-19_Free_and_Reduced_Lunch_Counts_by_School.xls", sheet_name=" Schools Data ")
for c in frl.columns:
    print(c)

Unnamed: 0
Unnamed: 1
Unnamed: 2
Unnamed: 3
Unnamed: 4
Unnamed: 5
Unnamed: 6
Unnamed: 7
Unnamed: 8
Unnamed: 9
Unnamed: 10

In [ ]:
frl_raw = pd.read_excel("/content/2018-19_Free_and_Reduced_Lunch_Counts_by_School.xls",
                         sheet_name=" Schools Data ", header=None)
print(frl_raw.head(10).to_string())

          0       1          2                            3                               4      5         6            7        8        9              10
0        NaN     NaN        NaN                          NaN                             NaN    NaN       NaN          NaN      NaN      NaN            NaN
1        NaN     NaN        NaN                          NaN                             NaN    NaN       NaN          NaN      NaN      NaN            NaN
2        NaN     NaN        NaN                          NaN                             NaN    NaN       NaN          NaN      NaN      NaN            NaN
3        NaN     NaN        NaN                          NaN                             NaN    NaN       NaN          NaN      NaN      NaN            NaN
4         FY  COUNTY  CODISTSCH                   SCHOOLNAME                      SCHOOLTYPE  GRADE  ENROLLED  FREEREDUCED  PERCENT  WARNING  CEP_Indicator
5  2018-2019   ADAMS  010003001     KENESAW SECONDARY SCHOOL  SECONDARY                       07-12       127           40    0.315      NaN           NONE
6  2018-2019   ADAMS  010003002    KENESAW ELEMENTARY SCHOOL  ELEMENTARY                      PK-06       149           49   0.3289      NaN           NONE
7  2018-2019   ADAMS  010018001  HASTINGS SENIOR HIGH SCHOOL  HIGH SCHOOL                     09-12      1045          568   0.5435      NaN           NONE
8  2018-2019   ADAMS  010018002       HASTINGS MIDDLE SCHOOL  MIDDLE SCHOOL                   06-08       761          479   0.6294      NaN           NONE
9  2018-2019   ADAMS  010018003     ALCOTT ELEMENTARY SCHOOL  ELEMENTARY                      PK-05       351          261   0.7436      NaN           NONE

In [ ]:
import pandas as pd
import os

base_path = "/content/"

frl_files = {
    "2018-19": "2018-19_Free_and_Reduced_Lunch_Counts_by_School.xls",
    "2019-20": "2019-20_Free_and_Reduced_Lunch_Counts_by_School.xls",
    "2020-21": "2020-21_Free_and_Reduced_Lunch_Counts_by_School.xls",
    "2021-22": "2021-2022_Free_and_Reduced_Lunch_Counts_by_School.xlsx",
    "2022-23": "2022-2023_Free_and_Reduced_Lunch_Counts_by_School.xlsx",
    "2023-24": "2023-2024_Free_and_Reduced_Lunch_Counts_by_School.xlsx",
    "2024-25": "2024-2025_Free_and_Reduced_Lunch_Counts_by_School.xlsx",
}

mem_files = {
    "2018-19": "MembershipByGradeRaceAndGender_20182019.csv",
    "2019-20": "MembershipByGradeRaceAndGender_20192020.csv",
    "2020-21": "MembershipByGradeRaceAndGender_20202021.csv",
    "2021-22": "MembershipByGradeRaceAndGender_20212022.csv",
    "2022-23": "MembershipByGradeRaceAndGender_20222023.csv",
    "2023-24": "MembershipByGradeRaceAndGender_20232024.csv",
    "2024-25": "MembershipByGradeRaceAndGender_20242025.csv",
}

def load_frl(year):
    path = base_path + frl_files[year]
    xl = pd.ExcelFile(path)
    sheet = [s for s in xl.sheet_names if "School" in s][0]
    raw = pd.read_excel(path, sheet_name=sheet, header=None)
    header_row = raw[raw.apply(lambda r: r.astype(str).str.contains("CODISTSCH|SCHOOLNAME", case=False).any(), axis=1)].index[0]
    df = pd.read_excel(path, sheet_name=sheet, header=header_row)
    df.columns = df.columns.str.strip()
    frl_col = [c for c in df.columns if "FREEREDUCED" in c.upper().replace(" ", "")]
    df["FREEREDUCED"] = df[frl_col[0]] if frl_col else None
    return df

def load_mem(year):
    df = pd.read_csv(base_path + mem_files[year])
    df.columns = df.columns.str.strip()
    return df

all_years = []

for year in frl_files.keys():
    frl = load_frl(year)
    mem = load_mem(year)

    frl = frl[["CODISTSCH", "COUNTY", "SCHOOLNAME", "SCHOOLTYPE", "GRADE", "ENROLLED", "FREEREDUCED", "PERCENT"]].copy()
    frl.columns = ["SCHOOL_ID", "COUNTY", "SCHOOL_NAME", "SCHOOL_TYPE", "GRADE", "ENROLLED", "FRL_COUNT", "FRL_PERCENT"]
    frl = frl[frl["SCHOOL_ID"].notna()]

    mem_grouped = mem.groupby("CO_DIST_SCH")["TOTAL"].sum().reset_index()
    mem_grouped.columns = ["SCHOOL_ID", "TOTAL_STUDENTS"]

    frl["SCHOOL_ID"] = frl["SCHOOL_ID"].astype(str).str.strip()
    mem_grouped["SCHOOL_ID"] = mem_grouped["SCHOOL_ID"].astype(str).str.strip()

    merged = pd.merge(frl, mem_grouped, on="SCHOOL_ID", how="left")
    merged["YEAR"] = year
    all_years.append(merged)
    print(f"{year} done — {len(merged)} rows")

final_df = pd.concat(all_years, ignore_index=True)
final_df = final_df[["SCHOOL_ID", "YEAR", "COUNTY", "SCHOOL_NAME", "SCHOOL_TYPE", "GRADE", "FRL_PERCENT", "FRL_COUNT", "ENROLLED", "TOTAL_STUDENTS"]]

final_df.to_csv("/content/final_panel_dataset.csv", index=False)
print(f"\nDone! Shape: {final_df.shape}")
print(f"Unique schools: {final_df['SCHOOL_ID'].nunique()}")
final_df.head()

2018-19 done — 1212 rows
2019-20 done — 1199 rows
2020-21 done — 1201 rows
2021-22 done — 1197 rows
2022-23 done — 1207 rows
2023-24 done — 1215 rows
2024-25 done — 1213 rows

Done! Shape: (8444, 10)
Unique schools: 1298

,SCHOOL_ID,YEAR,COUNTY,SCHOOL_NAME,SCHOOL_TYPE,GRADE,FRL_PERCENT,FRL_COUNT,ENROLLED,TOTAL_STUDENTS
0,10003001,2018-19,ADAMS,KENESAW SECONDARY SCHOOL,SECONDARY,07-12,0.315,40,127,NaN
1,10003002,2018-19,ADAMS,KENESAW ELEMENTARY SCHOOL,ELEMENTARY,PK-06,0.3289,49,149,NaN
2,10018001,2018-19,ADAMS,HASTINGS SENIOR HIGH SCHOOL,HIGH SCHOOL,09-12,0.5435,568,1045,NaN
3,10018002,2018-19,ADAMS,HASTINGS MIDDLE SCHOOL,MIDDLE SCHOOL,06-08,0.6294,479,761,NaN
4,10018003,2018-19,ADAMS,ALCOTT ELEMENTARY SCHOOL,ELEMENTARY,PK-05,0.7436,261,351,NaN

In [ ]:
print(frl["SCHOOL_ID"].head())
print(mem_grouped["SCHOOL_ID"].head())

0    10003001
1    10003002
2    10018001
3    10018002
4    10018003
Name: SCHOOL_ID, dtype: object
0    01-0003-001
1    01-0003-002
2    01-0018-001
3    01-0018-002
4    01-0018-003
Name: SCHOOL_ID, dtype: object

In [ ]:
import pandas as pd
import os

base_path = "/content/"

frl_files = {
    "2018-19": "2018-19_Free_and_Reduced_Lunch_Counts_by_School.xls",
    "2019-20": "2019-20_Free_and_Reduced_Lunch_Counts_by_School.xls",
    "2020-21": "2020-21_Free_and_Reduced_Lunch_Counts_by_School.xls",
    "2021-22": "2021-2022_Free_and_Reduced_Lunch_Counts_by_School.xlsx",
    "2022-23": "2022-2023_Free_and_Reduced_Lunch_Counts_by_School.xlsx",
    "2023-24": "2023-2024_Free_and_Reduced_Lunch_Counts_by_School.xlsx",
    "2024-25": "2024-2025_Free_and_Reduced_Lunch_Counts_by_School.xlsx",
}

mem_files = {
    "2018-19": "MembershipByGradeRaceAndGender_20182019.csv",
    "2019-20": "MembershipByGradeRaceAndGender_20192020.csv",
    "2020-21": "MembershipByGradeRaceAndGender_20202021.csv",
    "2021-22": "MembershipByGradeRaceAndGender_20212022.csv",
    "2022-23": "MembershipByGradeRaceAndGender_20222023.csv",
    "2023-24": "MembershipByGradeRaceAndGender_20232024.csv",
    "2024-25": "MembershipByGradeRaceAndGender_20242025.csv",
}

def normalize_id(x):
    return str(x).replace("-", "").strip().lstrip("0").zfill(8)

def load_frl(year):
    path = base_path + frl_files[year]
    xl = pd.ExcelFile(path)
    sheet = [s for s in xl.sheet_names if "School" in s][0]
    raw = pd.read_excel(path, sheet_name=sheet, header=None)
    header_row = raw[raw.apply(lambda r: r.astype(str).str.contains("CODISTSCH|SCHOOLNAME", case=False).any(), axis=1)].index[0]
    df = pd.read_excel(path, sheet_name=sheet, header=header_row)
    df.columns = df.columns.str.strip()
    frl_col = [c for c in df.columns if "FREEREDUCED" in c.upper().replace(" ", "")]
    df["FREEREDUCED"] = df[frl_col[0]] if frl_col else None
    return df

def load_mem(year):
    df = pd.read_csv(base_path + mem_files[year])
    df.columns = df.columns.str.strip()
    return df

all_years = []

for year in frl_files.keys():
    frl = load_frl(year)
    mem = load_mem(year)

    frl = frl[["CODISTSCH", "COUNTY", "SCHOOLNAME", "SCHOOLTYPE", "GRADE", "ENROLLED", "FREEREDUCED", "PERCENT"]].copy()
    frl.columns = ["SCHOOL_ID", "COUNTY", "SCHOOL_NAME", "SCHOOL_TYPE", "GRADE", "ENROLLED", "FRL_COUNT", "FRL_PERCENT"]
    frl = frl[frl["SCHOOL_ID"].notna()]

    mem_grouped = mem.groupby("CO_DIST_SCH")["TOTAL"].sum().reset_index()
    mem_grouped.columns = ["SCHOOL_ID", "TOTAL_STUDENTS"]

    frl["SCHOOL_ID"] = frl["SCHOOL_ID"].astype(str).apply(normalize_id)
    mem_grouped["SCHOOL_ID"] = mem_grouped["SCHOOL_ID"].astype(str).apply(normalize_id)

    merged = pd.merge(frl, mem_grouped, on="SCHOOL_ID", how="left")
    merged["YEAR"] = year
    all_years.append(merged)
    print(f"{year} done — {len(merged)} rows")

final_df = pd.concat(all_years, ignore_index=True)
final_df = final_df[["SCHOOL_ID", "YEAR", "COUNTY", "SCHOOL_NAME", "SCHOOL_TYPE", "GRADE", "FRL_PERCENT", "FRL_COUNT", "ENROLLED", "TOTAL_STUDENTS"]]

final_df.to_csv("/content/final_panel_dataset.csv", index=False)
print(f"\nDone! Shape: {final_df.shape}")
print(f"Unique schools: {final_df['SCHOOL_ID'].nunique()}")
final_df.head()

2018-19 done — 1212 rows
2019-20 done — 1199 rows
2020-21 done — 1201 rows
2021-22 done — 1197 rows
2022-23 done — 1207 rows
2023-24 done — 1215 rows
2024-25 done — 1213 rows

Done! Shape: (8444, 10)
Unique schools: 1298

,SCHOOL_ID,YEAR,COUNTY,SCHOOL_NAME,SCHOOL_TYPE,GRADE,FRL_PERCENT,FRL_COUNT,ENROLLED,TOTAL_STUDENTS
0,10003001,2018-19,ADAMS,KENESAW SECONDARY SCHOOL,SECONDARY,07-12,0.315,40,127,127
1,10003002,2018-19,ADAMS,KENESAW ELEMENTARY SCHOOL,ELEMENTARY,PK-06,0.3289,49,149,149
2,10018001,2018-19,ADAMS,HASTINGS SENIOR HIGH SCHOOL,HIGH SCHOOL,09-12,0.5435,568,1045,1045
3,10018002,2018-19,ADAMS,HASTINGS MIDDLE SCHOOL,MIDDLE SCHOOL,06-08,0.6294,479,761,761
4,10018003,2018-19,ADAMS,ALCOTT ELEMENTARY SCHOOL,ELEMENTARY,PK-05,0.7436,261,351,351

In [ ]:
xl = pd.ExcelFile("/content/2018-2019-Student-Absences-Counts-by-District.xlsx")
print(xl.sheet_names)

df = pd.read_excel("/content/2018-2019-Student-Absences-Counts-by-District.xlsx")
print(df.columns.tolist())
print(df.head())

['SUMMARY', 'DEMOGRAPHICS BY GRADE', 'COUNTY TOTAL', 'DISTRICT TOTAL', 'SCHOOL TOTAL', 'BY GRADE']
['NEBRASKA DEPARTMENT OF EDUCATION', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Run On: ', datetime.datetime(2023, 7, 23, 0, 0), 'Unnamed: 8', 'Unnamed: 9']
                    NEBRASKA DEPARTMENT OF EDUCATION Unnamed: 1 Unnamed: 2  \
0                     DATA, RESEARCH, AND EVALUATION        NaN        NaN
1  K-12 MEMBERSHIP AND STUDENTS WITH MORE THAN 10...        NaN        NaN
2  ABSENCES DATA FROM ADVISER: 2018-2019 STUDENT ...        NaN        NaN
3                                                NaN        NaN        NaN
4                                  STATEWIDE SUMMARY        NaN        NaN

  Unnamed: 3 Unnamed: 4 Unnamed: 5 Run On:  2023-07-23 00:00:00 Unnamed: 8  \
0        NaN        NaN        NaN      NaN                 NaN        NaN
1        NaN        NaN        NaN      NaN                 NaN        NaN
2        NaN        NaN        NaN      NaN                 NaN        NaN
3        NaN        NaN        NaN      NaN                 NaN        NaN
4        NaN        NaN        NaN      NaN                 NaN        NaN

  Unnamed: 9
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN

In [ ]:
df_raw = pd.read_excel("/content/2018-2019-Student-Absences-Counts-by-District.xlsx", header=None)
print(df_raw.head(20).to_string())

                                                                           0           1                                               2                                                 3                                               4                                                 5                                               6                                                 7                            8                               9
0                                           NEBRASKA DEPARTMENT OF EDUCATION         NaN                                             NaN                                               NaN                                             NaN                                               NaN                                        Run On:                                2023-07-23 00:00:00                          NaN                             NaN
1                                             DATA, RESEARCH, AND EVALUATION         NaN                                             NaN                                               NaN                                             NaN                                               NaN                                             NaN                                               NaN                          NaN                             NaN
2   K-12 MEMBERSHIP AND STUDENTS WITH MORE THAN 10/15/20 DAYS TOTAL ABSENCES         NaN                                             NaN                                               NaN                                             NaN                                               NaN                                             NaN                                               NaN                          NaN                             NaN
3                  ABSENCES DATA FROM ADVISER: 2018-2019 STUDENT  ATTENDANCE         NaN                                             NaN                                               NaN                                             NaN                                               NaN                                             NaN                                               NaN                          NaN                             NaN
4                                                                        NaN         NaN                                             NaN                                               NaN                                             NaN                                               NaN                                             NaN                                               NaN                          NaN                             NaN
5                                                          STATEWIDE SUMMARY         NaN                                             NaN                                               NaN                                             NaN                                               NaN                                             NaN                                               NaN                          NaN                             NaN
6                                                                        NaN         NaN                                             NaN                                               NaN                                             NaN                                               NaN                                             NaN                                               NaN                          NaN                             NaN
7                                                                        NaN         NaN                                             NaN                                               NaN                                             NaN                                     STUDENT COUNT                                 % OF MEMBERSHIP                                               NaN                          NaN                             NaN
8                                                                 MEMBERSHIP         NaN                                             NaN                                               NaN                                             NaN                                            307729                                             NaN                                               NaN                          NaN                             NaN
9                             STUDENTS WITH MORE THAN 10 DAYS TOTAL ABSENCES         NaN                                             NaN                                               NaN                                             NaN                                             92273                                        0.299851                                               NaN                          NaN                             NaN
10                            STUDENTS WITH MORE THAN 15 DAYS TOTAL ABSENCES         NaN                                             NaN                                               NaN                                             NaN                                             48705                                        0.158272                                               NaN                          NaN                             NaN
11                            STUDENTS WITH MORE THAN 20 DAYS TOTAL ABSENCES         NaN                                             NaN                                               NaN                                             NaN                                             28609                                        0.092968                                               NaN                          NaN                             NaN
12                                      STUDENTS THAT ARE CHRONICALLY ABSENT         NaN                                             NaN                                               NaN                                             NaN                                             45220                                        0.146947                                               NaN                          NaN                             NaN
13                                                                       NaN         NaN                                             NaN                                               NaN                                             NaN                                               NaN                                             NaN                                               NaN                          NaN                             NaN
14                                                                     GRADE  MEMBERSHIP  STUDENTS WITH MORE THAN 10 DAYS TOTAL ABSENCES  % STUDENTS WITH MORE THAN 10 DAYS TOTAL ABSENCES  STUDENTS WITH MORE THAN 15 DAYS TOTAL ABSENCES  % STUDENTS WITH MORE THAN 15 DAYS TOTAL ABSENCES  STUDENTS WITH MORE THAN 20 DAYS TOTAL ABSENCES  % STUDENTS WITH MORE THAN 20 DAYS TOTAL ABSENCES  STUDENTS CHRONICALLY ABSENT  % STUDENTS\nCHRONICALLY ABSENT
15                                                                        KG       22387                                            6012                                          0.268549                                            2607                                          0.116452                                            1198                                          0.053513                         2427                        0.108411
16                                                                        01       21995                                            5353                                          0.243373                                            2224                                          0.101114                                            1016                                          0.046192                         2076                        0.094385
17                                                                        02       21741                                            4686                                          0.215537                                            1905                                          0.087622                                             856                                          0.039373                         1732                        0.079665
18                                                                        03       22185                                            4905                                          0.221095                                            1979                                          0.089204                                             865                                           0.03899                         1816                        0.081857
19                                                                        04       22738                                            5144                                          0.226229                                            2055                                          0.090377                                             960                                           0.04222                         1844                        0.081098

In [ ]:
print(df_raw.iloc[14].tolist())
print(df_raw.iloc[15].tolist())

['GRADE', 'MEMBERSHIP', 'STUDENTS WITH MORE THAN 10 DAYS TOTAL ABSENCES', '% STUDENTS WITH MORE THAN 10 DAYS TOTAL ABSENCES', 'STUDENTS WITH MORE THAN 15 DAYS TOTAL ABSENCES', '% STUDENTS WITH MORE THAN 15 DAYS TOTAL ABSENCES', 'STUDENTS WITH MORE THAN 20 DAYS TOTAL ABSENCES', '% STUDENTS WITH MORE THAN 20 DAYS TOTAL ABSENCES', 'STUDENTS CHRONICALLY ABSENT', '% STUDENTS\nCHRONICALLY ABSENT']
['KG', 22387, 6012, 0.2685487113056685, 2607, 0.11645151203823648, 1198, 0.05351319962478224, 2427, 0.10841113146022245]

In [ ]:
xl = pd.ExcelFile("/content/2018-2019-Student-Absences-Counts-by-District.xlsx")
print(xl.sheet_names)

['SUMMARY', 'DEMOGRAPHICS BY GRADE', 'COUNTY TOTAL', 'DISTRICT TOTAL', 'SCHOOL TOTAL', 'BY GRADE']

In [ ]:
df_dist = pd.read_excel("/content/2018-2019-Student-Absences-Counts-by-District.xlsx",
                         sheet_name="DISTRICT TOTAL", header=None)
print(df_dist.head(20).to_string())

                                                                                         0                             1           2                                               3                                               4                                               5                6                                                 7
0                                                         NEBRASKA DEPARTMENT OF EDUCATION                           NaN         NaN                                             NaN                                        Run On:                              2023-07-23 00:00:00              NaN                                               NaN
1                                                           DATA, RESEARCH, AND EVALUATION                           NaN         NaN                                             NaN                                             NaN                                             NaN              NaN                                               NaN
2   K-12 MEMBERSHIP AND STUDENTS WITH MORE THAN 10/15/20 DAYS TOTAL ABSENCES - BY DISTRICT                           NaN         NaN                                             NaN                                             NaN                                             NaN              NaN                                               NaN
3                                ABSENCES DATA FROM ADVISER: 2018-2019 STUDENT ATTENDANCE                            NaN         NaN                                             NaN                                             NaN                                             NaN              NaN                                               NaN
4                                                                            DISTRICT CODE                 DISTRICT NAME  MEMBERSHIP  STUDENTS WITH MORE THAN 10 DAYS TOTAL ABSENCES  STUDENTS WITH MORE THAN 15 DAYS TOTAL ABSENCES  STUDENTS WITH MORE THAN 20 DAYS TOTAL ABSENCES  CHRONIC\nABSENT  % STUDENTS WITH MORE THAN 20 DAYS TOTAL ABSENCES
5                                                                              01-0003-000        KENESAW PUBLIC SCHOOLS         246                                               *                                               *                                               *                *                                                 *
6                                                                              01-0018-000       HASTINGS PUBLIC SCHOOLS        3336                                             876                                             405                                             204              427                                          0.061151
7                                                                              01-0090-000  ADAMS CENTRAL PUBLIC SCHOOLS         908                                             156                                              58                                              18               51                                          0.019824
8                                                                              01-0123-000    SILVER LAKE PUBLIC SCHOOLS         211                                              35                                              14                                               *               11                                                 *
9                                                                              02-0009-000        NELIGH-OAKDALE SCHOOLS         348                                              72                                              32                                              15               29                                          0.043103
10                                                                             02-0018-000          ELGIN PUBLIC SCHOOLS         138                                              27                                              11                                               *               12                                                 *
11                                                                             02-2001-000   NEBRASKA UNIFIED DISTRICT 1         395                                              69                                              27                                              12               18                                           0.03038
12                                                                             03-0500-000         ARTHUR COUNTY SCHOOLS         124                                              26                                              10                                               *               11                                                 *
13                                                                             04-0001-000  BANNER COUNTY PUBLIC SCHOOLS         120                                              24                                              11                                               *               10                                                 *
14                                                                             05-0071-000      SANDHILLS PUBLIC SCHOOLS          86                                              21                                               *                                               *                *                                                 *
15                                                                             06-0001-000         BOONE CENTRAL SCHOOLS         557                                             117                                              44                                              16               37                                          0.028725
16                                                                             06-0017-000      ST EDWARD PUBLIC SCHOOLS         168                                               *                                               *                                               *                *                                                 *
17                                                                             06-0075-000      RIVERSIDE PUBLIC SCHOOLS         207                                              30                                              15                                               *               15                                                 *
18                                                                             07-0006-000       ALLIANCE PUBLIC SCHOOLS        1313                                              22                                               *                                               *                *                                                 *
19                                                                             07-0010-000     HEMINGFORD PUBLIC SCHOOLS         423                                              56                                              28                                              16               25                                          0.037825

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [ ]:
absence_files = {
    "2018-19": "2018-2019-Student-Absences-Counts-by-District.xlsx",
    "2019-20": "2019-2020-Student-Absences-Counts-by-District.xlsx",
    "2020-21": "2020-2021-Student-Absences-Counts-by-District.xlsx",
    "2021-22": "2021-2022-Student-Absences-Counts-by-District.xlsx",
    "2022-23": "2022-2023-Student-Absences-Counts-by-District.xlsx",
    "2023-24": "2023-2024-Student-Absences-Counts-by-District.xlsx",
    "2024-25": "2024-2025-Student-Absences-Counts-by-District.xlsx",
}

def load_absence(year):
    path = "/content/" + absence_files[year]
    raw = pd.read_excel(path, sheet_name="DISTRICT TOTAL", header=None)
    header_row = raw[raw.apply(lambda r: r.astype(str).str.contains("DISTRICT CODE", case=False).any(), axis=1)].index[0]
    df = pd.read_excel(path, sheet_name="DISTRICT TOTAL", header=header_row)
    df.columns = df.columns.str.strip()
    df = df[df["DISTRICT CODE"].notna()]
    df = df[~df["DISTRICT CODE"].astype(str).str.contains("DISTRICT CODE", case=False)]

    chronic_col = [c for c in df.columns if "CHRONIC" in c.upper()]
    membership_col = [c for c in df.columns if c.strip().upper() == "MEMBERSHIP"]

    df["DISTRICT_ID"] = df["DISTRICT CODE"].astype(str).str.replace("-", "").str.strip()
    df["CHRONIC_ABSENT"] = pd.to_numeric(df[chronic_col[0]], errors="coerce")
    df["DISTRICT_MEMBERSHIP"] = pd.to_numeric(df[membership_col[0]], errors="coerce")
    df["CHRONIC_ABSENT_RATE"] = (df["CHRONIC_ABSENT"] / df["DISTRICT_MEMBERSHIP"]).round(4)
    df["YEAR"] = year

    return df[["DISTRICT_ID", "YEAR", "CHRONIC_ABSENT", "DISTRICT_MEMBERSHIP", "CHRONIC_ABSENT_RATE"]]

all_absence = []
for year in absence_files.keys():
    df = load_absence(year)
    all_absence.append(df)
    print(f"{year} — {len(df)} districts")

absence_panel = pd.concat(all_absence, ignore_index=True)
print(absence_panel.head())

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

2018-19 — 244 districts

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

2019-20 — 244 districts

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

2020-21 — 244 districts

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

2021-22 — 244 districts

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

2022-23 — 244 districts

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

2023-24 — 244 districts
2024-25 — 245 districts
  DISTRICT_ID     YEAR  CHRONIC_ABSENT  DISTRICT_MEMBERSHIP  \
0   010003000  2018-19             NaN                246.0
1   010018000  2018-19           427.0               3336.0
2   010090000  2018-19            51.0                908.0
3   010123000  2018-19            11.0                211.0
4   020009000  2018-19            29.0                348.0

   CHRONIC_ABSENT_RATE
0                  NaN
1               0.1280
2               0.0562
3               0.0521
4               0.0833

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [ ]:
final_df = pd.read_csv("/content/final_panel_dataset.csv")

final_df["DISTRICT_ID"] = final_df["SCHOOL_ID"].astype(str).str[:8].str.strip()
absence_panel["DISTRICT_ID"] = absence_panel["DISTRICT_ID"].astype(str).str.strip()

ml_df = pd.merge(final_df, absence_panel[["DISTRICT_ID", "YEAR", "CHRONIC_ABSENT_RATE"]],
                 on=["DISTRICT_ID", "YEAR"], how="left")

print(f"Shape: {ml_df.shape}")
print(f"Missing target: {ml_df['CHRONIC_ABSENT_RATE'].isna().sum()}")
print(ml_df[["SCHOOL_ID", "YEAR", "FRL_PERCENT", "CHRONIC_ABSENT_RATE"]].head(10))

Shape: (8444, 12)
Missing target: 8444
   SCHOOL_ID     YEAR FRL_PERCENT  CHRONIC_ABSENT_RATE
0   10003001  2018-19       0.315                  NaN
1   10003002  2018-19      0.3289                  NaN
2   10018001  2018-19      0.5435                  NaN
3   10018002  2018-19      0.6294                  NaN
4   10018003  2018-19      0.7436                  NaN
5   10018004  2018-19         0.5                  NaN
6   10018005  2018-19      0.9085                  NaN
7   10018006  2018-19      0.6173                  NaN
8   10018008  2018-19      0.5385                  NaN
9   10090001  2018-19      0.2146                  NaN

In [ ]:
print("Panel DISTRICT_ID sample:")
print(final_df["DISTRICT_ID"].head(10).tolist())

print("\nAbsence DISTRICT_ID sample:")
print(absence_panel["DISTRICT_ID"].head(10).tolist())

Panel DISTRICT_ID sample:
['10003001', '10003002', '10018001', '10018002', '10018003', '10018004', '10018005', '10018006', '10018008', '10090001']

Absence DISTRICT_ID sample:
['010003000', '010018000', '010090000', '010123000', '020009000', '020018000', '022001000', '030500000', '040001000', '050071000']

In [ ]:
# Absence: "010003000" → take chars 2-7 → "10003" → but panel has "10003001"
# Panel SCHOOL_ID "10003001" → first 5 chars = "10003" = district
# Absence DISTRICT_ID "010003000" → chars 1-6 = "100030" hmm

# Let's normalize both to just the 5-digit district code
final_df["DIST_KEY"] = final_df["SCHOOL_ID"].astype(str).str[1:6]
absence_panel["DIST_KEY"] = absence_panel["DISTRICT_ID"].astype(str).str[1:6]

print("Panel DIST_KEY:", final_df["DIST_KEY"].head(5).tolist())
print("Absence DIST_KEY:", absence_panel["DIST_KEY"].head(5).tolist())

Panel DIST_KEY: ['00030', '00030', '00180', '00180', '00180']
Absence DIST_KEY: ['10003', '10018', '10090', '10123', '20009']

In [ ]:
# Panel SCHOOL_ID "10003001" → strip leading 1 → "0003001" → first 5 = "00030"
# Absence DISTRICT_ID "010003000" → first 5 = "01000" nope
# Let's just strip ALL leading zeros and compare raw numbers

final_df["DIST_KEY"] = final_df["SCHOOL_ID"].astype(str).str[:5].str.lstrip("0")
absence_panel["DIST_KEY"] = absence_panel["DISTRICT_ID"].astype(str).str[:6].str.lstrip("0")

print("Panel DIST_KEY:", final_df["DIST_KEY"].head(5).tolist())
print("Absence DIST_KEY:", absence_panel["DIST_KEY"].head(5).tolist())

Panel DIST_KEY: ['10003', '10003', '10018', '10018', '10018']
Absence DIST_KEY: ['10003', '10018', '10090', '10123', '20009']

In [ ]:
ml_df = pd.merge(final_df, absence_panel[["DIST_KEY", "YEAR", "CHRONIC_ABSENT_RATE"]],
                 on=["DIST_KEY", "YEAR"], how="left")

print(f"Shape: {ml_df.shape}")
print(f"Missing target: {ml_df['CHRONIC_ABSENT_RATE'].isna().sum()}")
print(ml_df[["SCHOOL_ID", "YEAR", "FRL_PERCENT", "CHRONIC_ABSENT_RATE"]].head(10))

Shape: (8444, 13)
Missing target: 8083
   SCHOOL_ID     YEAR FRL_PERCENT  CHRONIC_ABSENT_RATE
0   10003001  2018-19       0.315                  NaN
1   10003002  2018-19      0.3289                  NaN
2   10018001  2018-19      0.5435               0.1280
3   10018002  2018-19      0.6294               0.1280
4   10018003  2018-19      0.7436               0.1280
5   10018004  2018-19         0.5               0.1280
6   10018005  2018-19      0.9085               0.1280
7   10018006  2018-19      0.6173               0.1280
8   10018008  2018-19      0.5385               0.1280
9   10090001  2018-19      0.2146               0.0562

In [ ]:
ml_df_clean = ml_df.dropna(subset=["CHRONIC_ABSENT_RATE"])

print(f"Final ML dataset shape: {ml_df_clean.shape}")
print(f"Unique schools: {ml_df_clean['SCHOOL_ID'].nunique()}")
print(f"Years: {ml_df_clean['YEAR'].unique()}")

ml_df_clean.to_csv("/content/final_ML_dataset.csv", index=False)
print("Saved!")
ml_df_clean.head()

Final ML dataset shape: (361, 13)
Unique schools: 73
Years: ['2018-19' '2019-20' '2020-21' '2021-22' '2022-23' '2023-24' '2024-25']
Saved!

,SCHOOL_ID,YEAR,COUNTY,SCHOOL_NAME,SCHOOL_TYPE,GRADE,FRL_PERCENT,FRL_COUNT,ENROLLED,TOTAL_STUDENTS,DISTRICT_ID,DIST_KEY,CHRONIC_ABSENT_RATE
2,10018001,2018-19,ADAMS,HASTINGS SENIOR HIGH SCHOOL,HIGH SCHOOL,09-12,0.5435,568,1045,1045,10018001,10018,0.128
3,10018002,2018-19,ADAMS,HASTINGS MIDDLE SCHOOL,MIDDLE SCHOOL,06-08,0.6294,479,761,761,10018002,10018,0.128
4,10018003,2018-19,ADAMS,ALCOTT ELEMENTARY SCHOOL,ELEMENTARY,PK-05,0.7436,261,351,351,10018003,10018,0.128
5,10018004,2018-19,ADAMS,HAWTHORNE ELEMENTARY SCHOOL,ELEMENTARY,PK-05,0.5,199,398,398,10018004,10018,0.128
6,10018005,2018-19,ADAMS,LINCOLN ELEMENTARY SCHOOL,ELEMENTARY,PK-05,0.9085,298,328,328,10018005,10018,0.128